Comic Book Gallery/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Comic_Book_Gallery.Models
{
    public class Artist
    {
        public string Name { get; set; }
        public string Role { get; set; }
    }
}

Comic Book Gallery/Models/ComicBook.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Comic_Book_Gallery.Models
{
    public class ComicBook
    {
        public int       Id { get; set; }
        public string    SeriesTitle { get; set; }
        public int       IssueNumber { get; set; }
        public string    DescriptionHtml { get; set; }
        public Artist[]  Artists { get; set; }
        public bool      Favorite { get; set; }

        public string DisplayText
        {
            get
            {
                return SeriesTitle + " #" + IssueNumber;
            }
        }

        // series-title-issunumber.jpg
        public string CoverImageFileName
        {
            get
            {
                return SeriesTitle.Replace(" ", "-").ToLower() + "-" + IssueNumber + ".jpg";
            }
        }
    }
}

Comic Book Gallery/Controllers/ComicBooksController.cs
/*


    - Controller classes/files must end with the word Controller.
    - The class and method must be public to be accessed by the browser.
    - Controller page can be accessed via url https://localhost:44355/ComicBooks/Detail/Id
                                              https://localhost:xxxxx/CntrlrName/MthdName/Id (id is optional)
    - Controller methods are called actions.    


    - URL routing = url to controller action.
    - Many websites can be hosted on the same machine using different port numbers.
    - 


    - ActionResult is mom class of RedirectResult, ContentResult and ViewResult.
    - Controller base class provides methods Content(string) and Redirect(string)
        
        
    - View goes to folder Views/Shared/Detail.cshtml


    - Data is defined at the controller and sent to the view.
    - ViewBag provides is a dynamic for this communication.


    - ViewBag vs Strongly typed view.


    - int? makes int nullable.

    
    - HttpNotFound() returns an action result


    - Using the Debugger.
    - Step into/over/out.

*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;   // System.Web.Mvc.Controller
using Comic_Book_Gallery.Data;
using Comic_Book_Gallery.Models;

namespace Comic_Book_Gallery.Controllers
{
    public class ComicBooksController : Controller
    {
        private ComicBookRepository _comicBookRepository = null;

        public ComicBooksController()
        {
            _comicBookRepository = new ComicBookRepository();
        }

        public ActionResult Index()
        {
            var comicBooks = _comicBookRepository.GetComicBooks();

            return View(comicBooks);
        }

        public ActionResult Detail(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var comicBook = _comicBookRepository.GetComicBook((int)id);

            return View(comicBook);

        }
    }
}

Comic Book Gallery/Views/ComicBooks/Detail.cshtml
@* This is a Razor-style comment in a CSHTML file *@

<!-- This is an HTML-style comment in a CSHTML file -->
<!-- This View coresponds to Controller ComicBook and its Action Detail -->

@*


    - Starting a line with @ specifies that we are using C#.
    - C# content is escaped. You need to use Html.Raw().
    - You can make changes in the View source and refresh the webpage without rerunning it.


    - Loop with @.
    - <ul> : unordered list
    - <li> : list item
    - Ctrl+K, Ctrl+C to comment out a block of code, and Ctrl+K, Ctrl+U to uncomment a block of code.
    - If in @.


    - ViewBag defined at controller and used here.
    - Because ViewBag is dynamic there is no InteliSense.
    - ViewBag properties are not case sensitive.


    - html, head, body live in html, contents below are rendered from RenderBody()


    - Adding strongly typed views (models to views)


    - @( C# code here ) if not all code is noticed.


*@

@model Comic_Book_Gallery.Models.ComicBook

@{
    ViewBag.Title = Model.DisplayText; // Tab title
}

<h2>@Model.DisplayText</h2>

<div class="row">
    <!-- boostrap css classes -->
    <div class="col-md-6">
        <div class="well">
            <h5><label>Series Title:</label> @Model.SeriesTitle</h5>
            <h5><label>Issue #:</label> @Model.IssueNumber</h5>
            <h5><label>Favorite:</label> @(Model.Favorite ? "Yes" : "No")</h5>
            @if (Model.Artists.Length > 0)
            {
                <h5>Artist:</h5>
                <div>
                    <ul>
                        @foreach (var artist in Model.Artists)
                        {
                            <li>@artist.Role: @artist.Name</li>
                        }
                    </ul>
                </div>
            }
        </div>
        <h5>Description</h5>
        <p>@Html.Raw(Model.DescriptionHtml)</p>
    </div>
    <div class="col-md-6">
        <img src="~/Images/@Model.CoverImageFileName"
             alt="@Model.DisplayText" class="img-responsive" />
    </div>
</div>

Comic Book Gallery/Views/ComicBooks/Index.cshtml
<!--

    - _ViewStart.cshtml was made automatically and layout did not have to be specified.


    - Default routing code at Global.asax.
    - Also routing options.
    - We need an Index Controller or change RouteConfig.cs to use the ComicBooks controller.


    - Creating an anonymous type
    - Html.ActionLink -> text to link
    - Url.Action -> imag to link

-->

@model Comic_Book_Gallery.Models.ComicBook[]

@{
    ViewBag.Title = "Comic Books";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    @foreach (var comicBook in Model)
    {
        <div class="col-md-3">
            <h4>@Html.ActionLink(comicBook.DisplayText,"Detail",new { id = comicBook.Id } )</h4>
            <a href="@Url.Action("Detail", new { id = comicBook.Id })">
                <img src="/Images/@comicBook.CoverImageFileName"
                     alt=@comicBook.DisplayText
                     class="img-responsive" />
            </a>
        </div>
    }
</div>

Comic Book Gallery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Comic Book Gallery</title>
    <link href="~/Content/site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Comic Book Gallery", "Index", "ComicBooks", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!-- Add menu items here -->
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Comic Book Gallery</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>